CI: added artifact validation
Closes #93, closes #120.

diff --git a/dmlex-v1.0/specification/Makefile b/dmlex-v1.0/specification/Makefile
--- a/dmlex-v1.0/specification/Makefile
+++ b/dmlex-v1.0/specification/Makefile
@@ -32,6 +32,38 @@ Makefile.dep: dmlex.xml $(SOURCE_XML) makedep.sh
 	echo -n "SOURCE_XML=" > $@
 	./makedep.sh >> $@
 
-.PHONY: clean
+.PHONY: clean validate_xml validate_json
 clean:
 	rm -f dmlex-v1.0-csd02.html dmlex-v1.0-csd02.pdf dmlex-v1.0-csd02.fo dmlex-v1.0-csd02.xml Makefile.dep dmlex_uml.svg dmlex_uml.pdf dmlex.dot dmlex.dot.content
+
+xmldep:
+	@python -c 'import xmlschema' 2>/dev/null || { echo "Python xmlschema module is not installed, cannot validate XML examples."; exit 2; }
+
+jsondep:
+	@python -c 'import jsonschema' 2>/dev/null || { echo "Python jsonschema module is not installed, cannot validate JSON examples."; exit 2; }
+
+validate_xml: xmldep validate_xml.py schemas/XML/dmlex.xsd schemas/XML/dmlex_no-crosslingual.xsd
+	@for xmlexample in examples/examples/source/*[0-9].xml; do \
+		echo validating "$$xmlexample"; \
+		./validate_xml.py schemas/XML/dmlex.xsd < "$$xmlexample" 2>/dev/null \
+		|| \
+		./validate_xml.py schemas/XML/dmlex_no-crosslingual.xsd < "$$xmlexample" 2>/dev/null \
+		|| { echo "validation of $$xmlexample failed -- none of the following validations succeeded:"; \
+		     echo ./validate_xml.py schemas/XML/dmlex.xsd "< $$xmlexample"; \
+			 echo ./validate_xml.py schemas/XML/dmlex_no-crosslingual.xsd "< $$xmlexample" ; \
+			 exit 3; \
+		   } \
+	done
+
+validate_json: jsondep validate_json.py schemas/JSON/dmlex.schema.json schemas/JSON/dmlex_no-crosslingual.schema.json
+	@for jsonexample in examples/examples/source/*[0-9].json; do \
+		echo validating "$$jsonexample"; \
+		./validate_json.py schemas/JSON/dmlex.schema.json < "$$jsonexample" 2>/dev/null \
+		|| \
+		./validate_json.py schemas/JSON/dmlex_no-crosslingual.schema.json < "$$jsonexample" 2>/dev/null \
+		|| { echo "validation of $$jsonexample failed -- none of the following validations succeeded:"; \
+		     echo ./validate_json.py schemas/JSON/dmlex.schema.json "< $$jsonexample"; \
+			 echo ./validate_json.py schemas/JSON/dmlex_no-crosslingual.schema.json "< $$jsonexample" ; \
+			 exit 4; \
+		   } \
+	done
